BardEnergy: 180
FastCarrot: 60
FleeceCostume: 120
GrapplingHook: 5
Immobilizer: 360
MushroomShield: 60
SpaceRocket: 30
StellarPearl: 8
SuperStand: 180
Switcher: 12
ViewChanger: 15
AntiTrapStar: 120
FakePearl: 80
AntiPearl: 360
TrapAxe: 6
ArmorThief: 180
Disturb: 120
FaithFish: 180
NinjaBone: 5

HCFactions: false
Bunkers: true